# Generated by Django 3.2.8 on 2021-11-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Judul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_1', models.TextField(max_length=150)),
                ('judul_2', models.TextField(max_length=150)),
            ],
        ),
    ]
