# Generated by Django 3.2.8 on 2021-12-07 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pembimbing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pembimbing_1', models.TextField(max_length=180)),
                ('pembimbing_2', models.TextField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('nim', models.IntegerField()),
                ('judul', models.CharField(max_length=200)),
                ('pembimbing_1', models.CharField(max_length=20)),
                ('pembimbing_2', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.IntegerField()),
                ('nama', models.CharField(max_length=50)),
                ('judul', models.CharField(max_length=200)),
                ('pembimbing_1', models.CharField(max_length=20)),
                ('pembimbing_2', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Judul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_1', models.TextField(default='', max_length=150)),
                ('judul_2', models.TextField(default='', max_length=150)),
                ('pemb_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mahasiswa.pembimbing')),
            ],
        ),
    ]
