# Generated by Django 3.2.8 on 2021-12-17 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='judul',
            name='id_pembimbing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mahasiswa.pembimbing'),
        ),
    ]
