# Generated by Django 3.2.8 on 2021-12-27 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='judul',
            old_name='judul_1',
            new_name='judul_ta',
        ),
        migrations.RemoveField(
            model_name='judul',
            name='judul_2',
        ),
    ]
