# Generated by Django 3.2.8 on 2021-12-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembimbing',
            name='pembimbing_1',
            field=models.TextField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='pembimbing',
            name='pembimbing_2',
            field=models.TextField(default='', max_length=180),
        ),
    ]
