# Generated by Django 3.2.10 on 2021-12-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='pembimbing_1',
            field=models.TextField(max_length=180),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='pembimbing_2',
            field=models.TextField(max_length=180),
        ),
    ]
