# Generated by Django 3.2.8 on 2021-12-16 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tendik', '0003_mahasiswamodel_id_pembimbing'),
        ('mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='judul',
            name='id_mahasiswa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tendik.mahasiswamodel'),
        ),
    ]
