# Generated by Django 3.2.9 on 2021-12-02 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembimbing',
            name='pembimbing_1',
        ),
        migrations.RemoveField(
            model_name='pembimbing',
            name='pembimbing_2',
        ),
        migrations.AddField(
            model_name='pembimbing',
            name='cek',
            field=models.CharField(default='', max_length=255),
        ),
    ]
