# Generated by Django 3.2.8 on 2021-12-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('nim', models.IntegerField()),
                ('judul', models.CharField(max_length=200)),
                ('pembimbing_1', models.CharField(max_length=20)),
                ('pembimbing_2', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.IntegerField()),
                ('nama', models.CharField(max_length=50)),
                ('judul', models.CharField(max_length=200)),
                ('pembimbing_1', models.CharField(max_length=20)),
                ('pembimbing_2', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='pembimbing',
            name='pembimbing_1',
            field=models.TextField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='pembimbing',
            name='pembimbing_2',
            field=models.TextField(default='', max_length=180),
        ),
    ]
