# Generated by Django 3.2.8 on 2021-12-31 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judul',
            name='mhs',
        ),
    ]
