# Generated by Django 3.2.8 on 2021-12-17 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0002_judul_id_pembimbing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='judul',
            old_name='id_pembimbing',
            new_name='pembimbing',
        ),
    ]
