# Generated by Django 3.2.8 on 2021-11-30 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0002_tugas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tugas',
        ),
    ]
