# Generated by Django 3.2.9 on 2021-12-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0002_auto_20211202_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembimbing',
            name='cek',
        ),
        migrations.AddField(
            model_name='pembimbing',
            name='pembimbing_1',
            field=models.TextField(default='', max_length=180),
        ),
        migrations.AddField(
            model_name='pembimbing',
            name='pembimbing_2',
            field=models.TextField(default='', max_length=180),
        ),
    ]
