# Generated by Django 3.2.9 on 2021-11-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0002_tugas'),
    ]

    operations = [
        migrations.CreateModel(
            name='pembimbing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pembimbing_1', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='tugas',
        ),
    ]
