# Generated by Django 3.2.8 on 2022-01-01 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0002_auto_20220101_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='judul',
            name='date_disetujui',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='judul',
            name='date_judul',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='judul',
            name='id_pembimbing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mahasiswa.pembimbing'),
        ),
        migrations.AddField(
            model_name='judul',
            name='status_judul',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='judul',
            name='judul_1',
            field=models.TextField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='judul',
            name='judul_2',
            field=models.TextField(default='', max_length=150),
        ),
    ]
