# Generated by Django 3.2.8 on 2021-12-17 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0003_rename_id_pembimbing_judul_pembimbing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judul',
            name='pembimbing',
        ),
    ]
