# Generated by Django 3.2.9 on 2021-11-30 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0003_auto_20211130_1225'),
        ('mahasiswa', '0003_delete_tugas'),
    ]

    operations = [
    ]
