# Generated by Django 3.2.8 on 2021-12-07 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0004_alter_judul_pemb_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judul',
            name='pemb_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sebagai', to='mahasiswa.pembimbing'),
        ),
    ]
