# Generated by Django 3.2.9 on 2021-12-02 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0004_proposal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='NIM',
            new_name='nim',
        ),
    ]
