# Generated by Django 3.2.9 on 2022-01-01 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0004_auto_20220101_1106'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bimbingan',
        ),
    ]
