# Generated by Django 3.2.8 on 2022-01-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0004_auto_20220101_1106'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bimbingan',
        ),
        migrations.AlterField(
            model_name='judul',
            name='status_judul',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
