# Generated by Django 3.2.9 on 2021-12-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0005_rename_nim_proposal_nim'),
    ]

    operations = [
        migrations.CreateModel(
            name='ta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('nim', models.IntegerField()),
                ('judul', models.CharField(max_length=200)),
                ('pembimbing_1', models.CharField(max_length=20)),
                ('pembimbing_2', models.CharField(max_length=20)),
            ],
        ),
    ]
