# Generated by Django 3.2.10 on 2021-12-31 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0005_sidang'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bimbingan',
        ),
    ]
