# Generated by Django 3.2.8 on 2022-01-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0006_auto_20220113_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='judul',
            old_name='judul_1',
            new_name='judul',
        ),
        migrations.RemoveField(
            model_name='judul',
            name='judul_2',
        ),
        migrations.AddField(
            model_name='judul',
            name='batasan',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='judul',
            name='latar_belakang',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='judul',
            name='rumusan_masalah',
            field=models.TextField(default='', max_length=500),
        ),
    ]
