# Generated by Django 3.2.8 on 2021-12-30 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PembimbingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('nip', models.IntegerField(unique=True)),
                ('nidn', models.IntegerField()),
                ('hp', models.BigIntegerField()),
                ('prodi', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MahasiswaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('nim', models.IntegerField(unique=True)),
                ('prodi', models.CharField(max_length=20)),
                ('fakultas', models.CharField(max_length=20)),
                ('kelas', models.CharField(max_length=3)),
                ('semester', models.IntegerField()),
                ('tahun_masuk', models.IntegerField(null=True)),
                ('judul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mahasiswa.judul')),
            ],
        ),
    ]
