# Generated by Django 3.2.8 on 2021-11-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('nim', models.IntegerField()),
                ('prodi', models.CharField(max_length=20)),
                ('fakultas', models.CharField(max_length=20)),
                ('kelas', models.CharField(max_length=3)),
                ('semester', models.IntegerField()),
                ('tahun_masuk', models.IntegerField(max_length=4)),
            ],
        ),
    ]
