# Generated by Django 3.2.8 on 2021-12-17 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0001_initial'),
        ('tendik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswamodel',
            name='id_pembimbing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tendik.pembimbingmodel'),
        ),
        migrations.AddField(
            model_name='pembimbingmodel',
            name='id_pembimbing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mahasiswa.pembimbing'),
        ),
        migrations.AlterField(
            model_name='mahasiswamodel',
            name='nim',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='pembimbingmodel',
            name='hp',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='pembimbingmodel',
            name='nidn',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='pembimbingmodel',
            name='nip',
            field=models.IntegerField(unique=True),
        ),
    ]
