# Generated by Django 3.2.8 on 2022-01-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.IntegerField(unique=True)),
                ('nidn', models.IntegerField()),
                ('hp', models.BigIntegerField()),
                ('nama', models.CharField(default='', max_length=50)),
                ('prodi', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='MahasiswaModel',
            new_name='Mahasiswa',
        ),
        migrations.DeleteModel(
            name='PembimbingModel',
        ),
    ]
