# Generated by Django 3.2.8 on 2021-12-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswamodel',
            name='nim',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='pembimbingmodel',
            name='hp',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='pembimbingmodel',
            name='nidn',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='pembimbingmodel',
            name='nip',
            field=models.IntegerField(unique=True),
        ),
    ]
