# Generated by Django 3.2.8 on 2021-12-06 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MahasiswaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('nim', models.IntegerField()),
                ('prodi', models.CharField(max_length=20)),
                ('fakultas', models.CharField(max_length=20)),
                ('kelas', models.CharField(max_length=3)),
                ('semester', models.IntegerField()),
                ('tahun_masuk', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PembimbingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('nip', models.IntegerField()),
                ('nidn', models.IntegerField()),
                ('npwp', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('prodi', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Mahasiswa',
        ),
    ]
