# Generated by Django 3.2.8 on 2021-11-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='tahun_masuk',
            field=models.IntegerField(null=True),
        ),
    ]
