# Generated by Django 3.2.8 on 2021-12-08 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tendik', '0002_auto_20211206_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembimbingmodel',
            name='npwp',
        ),
    ]
