# Generated by Django 3.2.8 on 2021-12-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendik', '0002_auto_20211217_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembimbingmodel',
            name='hp',
            field=models.BigIntegerField(),
        ),
    ]
