# Generated by Django 3.2.8 on 2021-12-16 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tendik', '0002_auto_20211215_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswamodel',
            name='id_pembimbing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tendik.pembimbingmodel'),
        ),
    ]
