# Generated by Django 3.2.8 on 2021-12-01 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tendik', '0002_alter_mahasiswa_tahun_masuk'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mahasiswa',
            new_name='MahasiswaModel',
        ),
    ]
