# Generated by Django 3.2.8 on 2021-12-17 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tendik', '0002_auto_20211217_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembimbingmodel',
            name='id_pembimbing',
        ),
    ]
