# Generated by Django 3.2.8 on 2021-12-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendik', '0003_rename_mahasiswa_mahasiswamodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PembimbingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('nip', models.IntegerField()),
                ('nidn', models.IntegerField()),
                ('npwp', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('prodi', models.CharField(max_length=20)),
            ],
        ),
    ]
