# Generated by Django 3.2.8 on 2021-12-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendik', '0004_alter_pembimbingmodel_hp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembimbingmodel',
            name='hp',
            field=models.IntegerField(unique=True),
        ),
    ]
