# Generated by Django 3.2.8 on 2021-12-03 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tendik', '0004_pembimbingmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembimbingmodel',
            name='npwp',
        ),
    ]
