# Generated by Django 3.2.8 on 2021-12-17 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tendik', '0003_alter_pembimbingmodel_hp'),
        ('tendik', '0003_alter_pembimbingmodel_nidn'),
        ('tendik', '0006_alter_pembimbingmodel_hp'),
    ]

    operations = [
    ]
