# Generated by Django 3.2.8 on 2021-12-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JadwalBimbingan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('waktu', models.TimeField()),
                ('lokasi', models.CharField(max_length=50)),
            ],
        ),
    ]
