# Generated by Django 3.2.8 on 2022-01-01 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pembimbing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PenyetujuanJudul',
        ),
    ]
