# Generated by Django 3.2.8 on 2022-01-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembimbing', '0002_delete_penyetujuanjudul'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenyetujuanJudul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=20)),
            ],
        ),
    ]
