# Generated by Django 3.2.8 on 2022-01-01 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0005_auto_20220101_1431'),
        ('pembimbing', '0003_penyetujuanjudul'),
    ]

    operations = [
        migrations.AddField(
            model_name='penyetujuanjudul',
            name='judul_id',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='mahasiswa.judul'),
        ),
        migrations.AddField(
            model_name='penyetujuanjudul',
            name='keterangan',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='penyetujuanjudul',
            name='judul',
            field=models.CharField(default='', max_length=20),
        ),
    ]
